/**
 */
package apssoftwareoptions.provider;

import apssoftwareoptions.util.ApssoftwareoptionsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ApssoftwareoptionsItemProviderAdapterFactory extends ApssoftwareoptionsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ApssoftwareoptionsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link apssoftwareoptions.APSReqSoftwareOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected APSReqSoftwareOptionItemProvider apsReqSoftwareOptionItemProvider;

	/**
	 * This creates an adapter for a {@link apssoftwareoptions.APSReqSoftwareOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAPSReqSoftwareOptionAdapter() {
		if (apsReqSoftwareOptionItemProvider == null) {
			apsReqSoftwareOptionItemProvider = new APSReqSoftwareOptionItemProvider(this);
		}

		return apsReqSoftwareOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link apssoftwareoptions.APSReqChangeSoftwareOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected APSReqChangeSoftwareOptionItemProvider apsReqChangeSoftwareOptionItemProvider;

	/**
	 * This creates an adapter for a {@link apssoftwareoptions.APSReqChangeSoftwareOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAPSReqChangeSoftwareOptionAdapter() {
		if (apsReqChangeSoftwareOptionItemProvider == null) {
			apsReqChangeSoftwareOptionItemProvider = new APSReqChangeSoftwareOptionItemProvider(this);
		}

		return apsReqChangeSoftwareOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link apssoftwareoptions.APSReqRemoveSoftwareOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected APSReqRemoveSoftwareOptionItemProvider apsReqRemoveSoftwareOptionItemProvider;

	/**
	 * This creates an adapter for a {@link apssoftwareoptions.APSReqRemoveSoftwareOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAPSReqRemoveSoftwareOptionAdapter() {
		if (apsReqRemoveSoftwareOptionItemProvider == null) {
			apsReqRemoveSoftwareOptionItemProvider = new APSReqRemoveSoftwareOptionItemProvider(this);
		}

		return apsReqRemoveSoftwareOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link apssoftwareoptions.APSReqReplaceSoftwareOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected APSReqReplaceSoftwareOptionItemProvider apsReqReplaceSoftwareOptionItemProvider;

	/**
	 * This creates an adapter for a {@link apssoftwareoptions.APSReqReplaceSoftwareOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAPSReqReplaceSoftwareOptionAdapter() {
		if (apsReqReplaceSoftwareOptionItemProvider == null) {
			apsReqReplaceSoftwareOptionItemProvider = new APSReqReplaceSoftwareOptionItemProvider(this);
		}

		return apsReqReplaceSoftwareOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link apssoftwareoptions.APSReqIntroduceNewSoftwareOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected APSReqIntroduceNewSoftwareOptionItemProvider apsReqIntroduceNewSoftwareOptionItemProvider;

	/**
	 * This creates an adapter for a {@link apssoftwareoptions.APSReqIntroduceNewSoftwareOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAPSReqIntroduceNewSoftwareOptionAdapter() {
		if (apsReqIntroduceNewSoftwareOptionItemProvider == null) {
			apsReqIntroduceNewSoftwareOptionItemProvider = new APSReqIntroduceNewSoftwareOptionItemProvider(this);
		}

		return apsReqIntroduceNewSoftwareOptionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (apsReqSoftwareOptionItemProvider != null) apsReqSoftwareOptionItemProvider.dispose();
		if (apsReqChangeSoftwareOptionItemProvider != null) apsReqChangeSoftwareOptionItemProvider.dispose();
		if (apsReqRemoveSoftwareOptionItemProvider != null) apsReqRemoveSoftwareOptionItemProvider.dispose();
		if (apsReqReplaceSoftwareOptionItemProvider != null) apsReqReplaceSoftwareOptionItemProvider.dispose();
		if (apsReqIntroduceNewSoftwareOptionItemProvider != null) apsReqIntroduceNewSoftwareOptionItemProvider.dispose();
	}

}
