<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modificationmarks_hardware" nsURI="http://www.example.org/modificationmarks_hardware"
    nsPrefix="modificationmarks_hardware">
  <eClassifiers xsi:type="ecore:EClass" name="APSReqHardwareSeedModifications" eSuperTypes="../../edu.kit.ipd.sdq.kamp4aps.model.modificationmarks/model/KAMP4aPSModificationsmarks.ecore#//KAMP4aPSSeedModifications ../../edu.kit.ipd.sdq.kamp4aps4req.model.modificationmarks/model/modificationmarks.ecore#//APSReqSeedModifications"/>
  <eClassifiers xsi:type="ecore:EClass" name="APSReqHardwareModificationRepository">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.model.modificationmarks/model/KAMP4aPSModificationsmarks.ecore#//AbstractKAMP4aPSModificationRepository">
      <eTypeArguments eClassifier="#//APSReqHardwareSeedModifications"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps4req.model.modificationmarks/model/modificationmarks.ecore#//AbstractKAMP4aPS4ReqModificationRepository">
      <eTypeArguments eClassifier="#//APSReqHardwareSeedModifications"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APSReqHardwareChangePropagationDueToSpecificationDependencies"
      eSuperTypes="../../edu.kit.ipd.sdq.kamp4aps4req.model.modificationmarks/model/modificationmarks.ecore#//AbstractAPSReqChangePropagationDueToSpecificationDependencies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structureModifications"
        upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.model.modificationmarks/model/KAMP4aPSModificationsmarks.ecore#//ModifyStructure">
        <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.aps/model/aPS.ecore#//StructureRepository/Structure"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleModifications" upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.model.modificationmarks/model/KAMP4aPSModificationsmarks.ecore#//ModifyModule">
        <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.aps/model/aPS.ecore#//ModuleRepository/Module"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentModifications"
        upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.model.modificationmarks/model/KAMP4aPSModificationsmarks.ecore#//ModifyComponent">
        <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.aps/model/aPS.ecore#//ComponentRepository/Component"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceModifications"
        upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.model.modificationmarks/model/KAMP4aPSModificationsmarks.ecore#//ModifyInterface">
        <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.aps/model/aPS.ecore#//InterfaceRepository/Interface"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
