<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="apshardwareoptions" nsURI="http://www.example.org/apshardwareoptions"
    nsPrefix="apshardwareoptions">
  <eClassifiers xsi:type="ecore:EClass" name="APSReqHardwareOption">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.basic/model/basic.ecore#//Entity"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../toometa.apsoptions/model/apsoptions.ecore#//APSReqOption">
      <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.basic/model/basic.ecore#//Entity"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APSReqIntroduceNewHardwareOption">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.basic/model/basic.ecore#//Entity"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1">
      <eGenericType eTypeParameter="#//APSReqIntroduceNewHardwareOption/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//APSReqHardwareOption">
      <eTypeArguments eTypeParameter="#//APSReqIntroduceNewHardwareOption/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APSReqRemoveHardwareOption">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.basic/model/basic.ecore#//Entity"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1">
      <eGenericType eTypeParameter="#//APSReqRemoveHardwareOption/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//APSReqHardwareOption">
      <eTypeArguments eTypeParameter="#//APSReqRemoveHardwareOption/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APSReqChangeHardwareOption">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.basic/model/basic.ecore#//Entity"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1">
      <eGenericType eTypeParameter="#//APSReqChangeHardwareOption/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//APSReqHardwareOption">
      <eTypeArguments eTypeParameter="#//APSReqChangeHardwareOption/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APSReqReplaceHardwareOption">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4aps.basic/model/basic.ecore#//Entity"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldEntity">
      <eGenericType eTypeParameter="#//APSReqReplaceHardwareOption/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newEntity">
      <eGenericType eTypeParameter="#//APSReqReplaceHardwareOption/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//APSReqHardwareOption">
      <eTypeArguments eTypeParameter="#//APSReqReplaceHardwareOption/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
